package dev.kamal.design_parking_lot.models;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class Ticket extends BaseModel{
    private String tickedNumber; // Random string of 7 characters
    private Date entryTime;
    private ParkingSpot parkingSpot;
    private Vehicle vehicle;
    private Gate entryGate;
    private Gate generatedAt;
    private Operator generatedBy;

    @Override
    public String toString() {
        return "\n" +
                "Parking At: " + this.getGeneratedAt().getParkingLot().getName() + "\n" +
                "Ticket Number: " + tickedNumber  + "\n" +
                "Entry Time: " + entryTime + "\n" +
                "Parking Spot: " + parkingSpot + "\n" +
                "Vehicle Number: " + vehicle + "\n" +
                "Vehicle Type: " + vehicle.getVehicleType() + "\n" +
                "Owner Name: " + vehicle.getOwnerName() + "\n" +
                "Generated At Gate: " + generatedAt + "\n" +
                "Generated By: " + generatedBy;
    }

}
